### ISSUE TITLE
(WBS 1.15.8) Create new key/value pairs to facilitate language translation and updates

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#166]
Currently, the site contains some controlled system language in the form of key/value pairs (see https://help.hubzero.org/documentation/22/webdevs/modules/languages). You can also see a list of all of the .ini files, of which we have both English and French versions, where these key/value pairs are stored across the site: https://github.com/search?q=repo%3Aetcluvic%2Fhsscommons+language%3AINI&type=code. 

The problem, however, is that some text on the site is plain text, so when we switch languages using the language switcher (via the language drop-down menu in the top-right corner of most pages), that text is not translated. In those cases, the page's template needs to be updated so that the plain text is converted into a key/value pair; this would enable those bits of untranslated text to change according to the currently selected language.

There are quite a few places across the site where we will slowly want to convert plain text into value pairs, but for now we can focus on publication landing pages as a test case. See, for example, https://hsscommons.ca/fr/publications/335/2. In the following screenshot of that page, I've used red circles to highlight text that needs to be converted to a key/value pair in both the English and French .ini files for this page, so that we can add in its French equivalent.

<img width="2017" alt="Screenshot 2024-01-03 at 3 06 57 PM" src="https://github.com/etcluvic/hsscommons/assets/12787016/365ef801-b9dc-4525-8da4-d9eab91b816b">

Once we've got new key/value pairs for these bits of text, I can provide French translations for them (for now, you can just use translation software to come up with placeholder text).

**Comment by ghjensen** [comment]
Oh, I almost forgot! If it's helpful, HUBzero's documentation also contains some suggestions regarding working with .ini files: https://help.hubzero.org/documentation/210/webdevs/basics/languages.

**Comment by kgosal03** [comment]
I think this one is merged in the test by you @ghjensen ? Will discuss if that is what you were looking for during the meeting tomorrow.

**Comment by ghjensen** [comment]
Thanks, @kgosal03. Again, the changes you made to the publications page look great!

As discussed, we're in the process of translating more of the site into French (and soon, Spanish). While we're waiting for that work to be completed, there are a couple of places where new key/value pairs could be created:

1. The main menu / navigation bar (every page; currently the text links are in both English and French, but we'd like to streamline this and make it so that only one or the other displays at a time, depending on which language is selected)
2. The footer menu (every page; again, currently in both English and French)
3. The Community landing page (https://hsscommons.ca/en/community)

In a minute, I'll send you a private message with the link to a spreadsheet containing all of the English/French values you can use when creating the new key/value pairs. Thanks for chipping away at this when you have some time!

**Comment by ghjensen** [comment]
I believe all of the above items have now been created in both French and English. Thanks again, Karan!
