### ISSUE TITLE
(WBS 1.9.46) Improve styling for "following" and "followers" lists

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#167]
When you have followed other members and have members following you, you can view their names by going to your profile and clicking the text links near the top-left corner of the page (with numbers and then the text "following" and "followers"). Currently, when you hover over someone's name, the text colour changes and an underline appears below the text. However, this could be styled to look a bit better--and also prevent the slight shift/flicker effect that occurs when the 1px border is added to the links. Could we try removing the bottom border and replacing it with either: (a) subtly darker background colour for the whole block element (while keeping the text colour dark enough so that there's still a good amount of contrast); or (b) some other styling that you think would like good and still retain a good amount of contrast?

Screenshot of current link styling:
<img width="1407" alt="Screenshot 2024-01-03 at 3 32 25 PM" src="https://github.com/etcluvic/hsscommons/assets/12787016/1413dcb4-b95f-4ae9-9417-76083bc34411">

**Comment by kgosal03** [comment]
<img width="330" alt="image" src="https://github.com/etcluvic/hsscommons/assets/45154385/703ef4f7-fff2-4bc2-8de1-665c14ac87ee">

I have changed the style to this @ghjensen . Let me how this looks. I am happy to make any other adjustments if there is something else you like to add or remove in the styling.
[
Branch Link](https://github.com/etcluvic/hsscommons/pull/177)

**Comment by kgosal03** [comment]
Another one is this @ghjensen with transition added
<img width="351" alt="image" src="https://github.com/etcluvic/hsscommons/assets/45154385/5feb669b-0605-4a49-b685-8347cd4aa4b1">

I removed the bold in this case.

**Comment by ghjensen** [comment]
Thanks, @kgosal03—these look great! I think the block elements with slightly rounded corners look great. Could we...

1. keep the bold text for the link text (in both normal and hover states) but;
2. change the text color to #FFFFFF and background colour to #456084? (I ran a Color Contrast test and think these changes should help us score better for accessibility testing. For reference, I used https://www.audioeye.com/color-contrast-checker.)

Let me know what you think! Also, one last request: for this change and future changes, could you please merge your branches into the test branch instead of the h2.2.22 branch? We need to merge changes into the test branch for them to show up on the test server. Thanks!

**Comment by kgosal03** [comment]
Yeah, the changes you suggested look great. I have made the changes in the i167 branch. My apologies for that. There is some error I am getting when I try to merge to the test, will resolve it tomorrow. The 167 is up to date with the final changes. I will merge the final changes into test tomorrow.

**Comment by ghjensen** [comment]
Thanks, Karan! I think it's all ready to add to production with our next update.
