### ISSUE TITLE
(WBS 1.4.9) Fix "Create or Connect your ORCID iD" button

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#180]
On the registration page (https://hsscommons.ca/en/register/), there's a button beside the "ORCID" field. Currently, the text spills outside of the button's borders, and if the page is resized or displayed in a narrow browser window, the text spills out even more (see screenshot below). Could we fix the CSS for this button so that the text all fits inside, regardless of the window width? We could also make the ORCID text field narrower to provide more space for the button, since ORCID IDs do not require nearly that much space.

![Screenshot 2024-03-04 at 4 33 07 PM](https://github.com/etcluvic/hsscommons/assets/12787016/a5300657-12a5-49d1-82a1-15231d77bbce)

**Comment by kgosal03** [comment]
@ghjensen This issue is fixed and the changes are in the test branch. I restarted the test server and you can see the changes live. Let me know me if the changed version is what you wanted. Now, both the button and input are aligned and of equal size. Thanks

**Comment by ghjensen** [comment]
This looks much better! Thanks, Karan. Soon I'll send UVic Systems an update request to merge test into production, at which point I'll mark this Issue completed.
