### ISSUE TITLE
(WBS 1.14.68) Change Twitter logo to X logo and clean up sharing icons

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#182]
It's probably time for us to admit that Twitter is fully dead and X is here to stay. Can we change the Twitter logo used on the site to the X logo? I believe it's currently used in two places (but it may be worth doing a search of the codebase for other instances):

1. The sharing bar for repository publications (connected to plg_publications_share), like the one you can see in the top-right corner of this page: https://hsscommons.ca/en/publications/53/1 
2. The sharing bar for individual and site-wide blog posts, such as [this site-wide post](https://hsscommons.ca/en/blog/2024/02/the-canadian-hss-commons-community-over-commercialization) and [this personal post](https://hsscommons.ca/en/members/1417/blog/2023/10/global-equity-in-open-access-publishing)

If possible, it would be great if we could also fix the vertical alignment and sizing of the "Copy URL" to match the icons/logos (which may require us to increase the icon size slightly). Here's what the sharing icons currently look like for me on Mac/Chrome:
![Screenshot 2024-03-08 at 10 28 01 AM](https://github.com/etcluvic/hsscommons/assets/12787016/bfe573ed-89a8-42fc-b551-066653d849cd)

**Comment by kgosal03** [comment]
<img width="251" alt="image" src="https://github.com/etcluvic/hsscommons/assets/45154385/5b92c1f4-504f-47ab-a076-dfa0560ad8db">


Hi Graham! Let me know how this looks to you.

It was tricky how the things were set as some icons were images and some are unicode maybe from font awesome. I added my own image for email as the old one was two images in one(two icons vertically oriented in one image shown by hiding the one of the images using CSS).

I haven't merged into test yet so if you like it then I will merge and you can play around.

**Comment by ghjensen** [comment]
Hey Karan, thanks for your work on this! I like the larger icons, and I think the X logo you chose should work well. I have just a few small suggestions, if that's not too annoying: 

1. Would it be possible to make the icons all the same size, even if you need to convert some to image form? That way we could align them vertically to match up perfectly (for the icons at least, but maybe not the "Copy DOI" button).
2. Could we add a white/near-white background to the email icon, just to make it stand out more against the blue background?
3. Could we try changing the colours of the "Copy DOI" button to match the envelope colours (i.e., #223b4a or similar for the border and text, and white/near-white for the background)?

I think #2 and #3 should be fairly easy to implement, but let me know if #1 proves difficult!

**Comment by kgosal03** [comment]
<img width="438" alt="image" src="https://github.com/etcluvic/hsscommons/assets/45154385/c20cbd82-68ea-41d8-b631-0b49148bf7aa">


How is this one looking @ghjensen ? It is super tricky. I tried to add the background to the old envelope but there are some other issues so need to switch to this icon. Also adjusted the size of copy doi button.

Let me know if any other changes you like or something you don't like.

**Comment by ghjensen** [comment]
Thanks, @kgosal03! I think that looks better. Perhaps we can try this on the test branch now to see how it looks there?

**Comment by kgosal03** [comment]
Sure @ghjensen . I will merge it and run the restart the server and then let you know once done.

**Comment by kgosal03** [comment]
The changes are merged @ghjensen and are live on the test server.

**Comment by ghjensen** [comment]
I think that looks great, Karan! Thanks so much. Just one last question, out of curiosity: could we use an envelope image without the "E" for the email link? Not sure if that's an option, but if it is that would be my preference.

**Comment by kgosal03** [comment]
Sure @ghjensen , I will give it a shot to edit the envelope as we don't have an option for one without the email link. The other one we have is the one that I added earlier but the background color won't be added on that as it creates other issues. I can try to change the code for the envelope. Let's see what I can do. Thanks 👍

**Comment by kgosal03** [comment]
I have updated the email icon @ghjensen . It is live on the test server. Let me know if that works. 👍

**Comment by ghjensen** [comment]
Everything looks good on prod, too, so I'm closing this issue. Thanks again!
