### ISSUE TITLE
Improve UI for Tags tab during publication process

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#193]
**Context:** When you're publishing an item in the repository, you have to go through a series of pages/tabs to enter information about the publication. At the bottom of the tab, there are two buttons, "Apply changes" and "Next." Usually, when you press "Next," it will save the information you've added and _then_ take you to the next tab. However, the "Tags" tab behaves differently: it doesn't save inputted information before moving you to the next tab, so if you don't hit "Apply changes" first, you have to re-enter that information.

You can see this issue in the following video, starting at around 0:50 (the video was actually created to document a different issue, so the first part isn't relevant): https://drive.google.com/file/d/1WNKIAJJFsgA5V2jXf6CqI2pzH2RhvIjE/view.

**Request:** Could we fix the Tags tab so that it behaves like the other publication pages and automatically applies changes when you press the "Next" button? (Important note: from what I can tell, the publication process for publications that are created through a project doesn't seem to have this issue, so you might be able to compare the code for individual publications and project publications to see if the project publications code has a solution. In any case, we'll need to test any fix for both kinds of publications.)

**Comment by kgosal03** [comment]
https://github.com/etcluvic/hsscommons/assets/45154385/45ccca89-fb14-41fd-9919-0e53cf89e4ac

Hi @ghjensen! I was trying to reproduce this issue on both ways of publishing directly as well through a project. However, I am not able to reproduce it. I have tried few times and on different browsers(Chrome and Edge) thinking it might be a browser issue. If you think I am missing something please let me know.

**Comment by ghjensen** [comment]
Hi @kgosal03! Weird. I can't reproduce the issue now, either (I tried Chrome and Safari). Next week I'll talk to the team member who recorded the video linked above and see if he's still running into the same issue.

**Comment by ghjensen** [comment]
Ah--we figured it out. The "Next" button at the bottom of the page works, but it doesn't save your inputs if you click on one of the navigation tab links above the green box instead (for example, the "Notes" tab, which is the next tab after "Tags"). It behaves that way on both test and prod, so we'd like to fix it in both places. When you click any of those links at the top, it should save whatever you've inputted before it takes you to the next page, just like the "Next" and "Apply Changes" buttons do.

**Comment by kgosal03** [comment]
@ghjensen This should be good to go! I have tested it and it works well on my local VM and test server.

**Comment by ghjensen** [comment]
Thanks, Karan! It looks good to go on my end, too, so I'll create a PR to merge this into the h2.2.22 branch and have it updated on prod. :)
