### ISSUE TITLE
Fix "More" text visibility issue on Knowledge Base page

### ISSUE THREAD

**Issue by toanhminh0412** [etcluvic/hsscommons#20]
The **More** text should only appear for categories with more than 3 items

**Comment by toanhminh0412** [comment]
On `test` branch: **More** appears on every category
On `h2.2.22` branch: **More** doesn't appear at all

**Comment by toanhminh0412** [comment]
Hopefully fixed in pull request #21

**Comment by ghjensen** [comment]
Fixed!
