### ISSUE TITLE
Comment out Recommendations / Powered by block

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#230]
Every item in our repository currently has a "Recommendations" section with a strange bar/rectangle and a "Powered by..." link. For example,

<img width="945" alt="Screenshot 2024-10-21 at 10 53 26 AM" src="https://github.com/user-attachments/assets/71878cb8-9d22-4ad6-bb44-a622695e92c1">

Since the "Powered by..." link is currently broken and we don't have any immediate plans for devising/introducing a new recommendations system for publications, could we comment out or delete this block (basically everything circled in red in the screenshot)?

**Comment by leenapthine** [comment]
I was able to handle this one in admin backend.
