### ISSUE TITLE
WBS 1.11.11: Fix "Featured Projects" on home page

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#27]
The "Featured publications" on the home page seem to randomize as expected, but the "Featured projects" do not. This box only shows the same project—the most recent "public" project that was created, I believe. Refreshing the page does nothing.

Note: we need to do further testing to determine what determines whether a project is featured, since the "featured"/starred column in the admin interface doesn't match up with the projects featured in this part of the site.

See https://github.com/etcluvic/hsscommons/commit/10a64eb6b1c05678d2654c4b25291f583c3e3b9d.

**Comment by toanhminh0412** [comment]
How do you make featured publications and featured projects to appear on the Homepage? It doesn't appear that way on the dev server.
![image](https://user-images.githubusercontent.com/55383509/218227835-b9c8e93e-52dd-48c7-ac37-7d0f74775b12.png)

**Comment by ghjensen** [comment]
The screenshot you shared looks like it may be from dev.hsscommons.ca (our former dev instance), rather than test.hsscommons.ca (our current dev instance). If you look at either our current dev site or our prod site, you should be able to see the "Featured projects" box.

**Comment by toanhminh0412** [comment]
This screenshot is from my own dev server. I'm trying to replicate this on the dev server, so that I can start fixing this issue. How do I make the **featured projects** and **featured publications** appear on the Homepage using the CMS, i.e. the administrator page

**Comment by toanhminh0412** [comment]
Some further investigations tell me that this has something to do with the database migration as I can't find a module **Featured Project** or **mod_featuredproject** under **Module Manager** in the CMS. However I do find a `mod_featuredproject` folder in the `app` directory. So for me to access this module, I need to migrate this module to the CMS database. I'm not sure how to do that unfortunately :(. If you know, please show me. Otherwise, I don't think I can help with this issue

**Comment by toanhminh0412** [comment]
Please ignore the above, I figured out a way to have the module running now. Sorry for the confusion!

**Comment by ghjensen** [comment]
Thanks for following up, Archie. You're right: in the admin interface we just set the "Featured Project" module (the one you found in the app directory) to "Enabled" from the Module Manager. But I'm glad you found another way the run it!

**Comment by toanhminh0412** [comment]
Based on what I've read from the code, currently only one project is displayed for the featured projects. This project is the first project of all projects sorted by title. I don't know how to make only starred projects appear (unless I can see the database), but I can make public projects appear, sorted by whatever (title, created date, id, ...), and make more than one projects appear if needed

**Comment by ghjensen** [comment]
Ok, that's helpful to know! Would it be possible to make it so that the project listed in the "Featured Project" box is chosen from random when the page is refreshed (pulling either from the list of all _public_ projects or all _starred_ projects)? If you would need any additional access or files to look into that, let me know.

**Comment by toanhminh0412** [comment]
Sure, I'll see what I can come up with. I don't need access to other resources for now. How many projects would you like to be displayed?

**Comment by ghjensen** [comment]
Just one project at a time would be good (i.e., the same as in the "Featured Publications" box to the left).

**Comment by toanhminh0412** [comment]
ok sounds good

**Comment by toanhminh0412** [comment]
Should be fixed in PR #32

**Comment by ghjensen** [comment]
This has now been updated on prod. The randomization now works (hooray!), but there are still two remaining bugs:

1. For some reason not all public projects seem to be shown (it's rotating through just a few, even though there are many public projects: https://hsscommons.ca/projects/browse);
2. One of the projects it features has the status "Setup in progress" in the admin interface; it hasn't been setup completely, so it shows a 404 error when clicked.

**Comment by toanhminh0412** [comment]
Thanks for the feedback. Sorry that I can't work on this issue any further until I have access to a dev server that looks like the test or prod server.

**Comment by ghjensen** [comment]
No problem at all! Thanks so much for the progress you've made on this already.
