### ISSUE TITLE
Improve display of "My Projects" and "Public Projects"

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#29]
On https://hsscommons.ca/projects, the projects listed under "My Projects" (when you're logged in and have projects linked to your account) display in a single column. Ideally, we could set breakpoints so that the layout is responsive and multiple projects are listed here side by side, adjusting dynamically according to the size of the browser window.

Similarly, if you follow the "Browse Public Projects" link, you also get a single-column list of projects. This could also be improved with a responsive layout/breakpoints (and better spacing between projects; currently the padding or margins is very minimal).

<img width="1928" alt="Screen Shot 2023-02-03 at 10 03 13 AM" src="https://user-images.githubusercontent.com/12787016/216675871-0f3f42c6-a57a-4324-b939-5a8c846be5b0.png">

**Comment by toanhminh0412** [comment]
Please check out pull request #31

**Comment by ghjensen** [comment]
This has now been updated on the prod site and looks great! Thanks again, @toanhminh0412. :)
