### ISSUE TITLE
Folder icon size for publications

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#37]
When publishing items via the Commons, members are asked to "Add a file" (see the Content tab). When they click this, though, it is difficult to select the right file to attach because the folder icons are way too big. Screenshot:
 
<img width="774" alt="Screen Shot 2023-03-10 at 12 33 25 PM" src="https://user-images.githubusercontent.com/12787016/224423608-303677b1-af8d-42fa-8643-4f951440987b.png">

Is there a way to shrink the folder icons so that showing/hiding things using the folder arrows and selecting files is more user-friendly?

**Comment by toanhminh0412** [comment]
Please check out PR#39
