### ISSUE TITLE
WBS 1.2.1 - Add/edit meta tags

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#38]
In the backend, if you go to Site > Global Configuration and then look at “Metadata Settings”, it looks like you can edit the Site Meta Description and Site Meta Keywords. However, it seems that adding them here, via the admin interface, doesn't work; the new keywords just get erased when you click "Save," and we don't know why.

Could these tags be edited in the same way that we added the favicon recently? Would updating the "MetaDesc" and "MetaKeys" values in bootstrap/install/config/meta.php work?

**Comment by toanhminh0412** [comment]
I can't replicate this problem on my dev server. After adding a meta tag and clicking "Saved", those newly created tags are still there for me.
![image](https://user-images.githubusercontent.com/55383509/224825134-9e2d5314-65dc-489d-b621-dcadcd83052c.png)
`config/meta.php` is automatically updated for me too
![image](https://user-images.githubusercontent.com/55383509/224825930-23abe0bb-1b49-4323-81d7-8472375cd553.png)

**Comment by ghjensen** [comment]
This works for me on the test instance, too, but not on the production instance. On the production instance, whatever I enter in the meta fields still gets erased every time I press "Save" or "Save & Close."

**Comment by toanhminh0412** [comment]
Honestly I don't know what to do in this case. I need to have a server similar to the production server to fix this :(
Can you change the code in `meta.php` on the production server?

**Comment by ghjensen** [comment]
That's a good question! And understood that you can't fix something that's not broken on your dev server. I'll check to see if I can get access to the meta.php file...

**Comment by ghjensen** [comment]
Done! Matthew was able to update the meta.php directly. :)

**Comment by toanhminh0412** [comment]
Yay amazing!
